#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
.. module:: dump_dxfile.py
   :platform: Unix
   :synopsis: log.infoan hdf5 file Group/Data dataset list.

"""

from __future__ import print_function

import os
import h5py
import sys
import argparse
import dxchange
import dxchange.reader as dxreader

import log
import pathlib
from datetime import datetime
import numpy as np


def main(arg):

    parser = argparse.ArgumentParser()
    parser.add_argument("fname", help="DataExchange file: /data/sample.h5")

    args = parser.parse_args()

    # Set path to the micro-CT data to reconstruct.
    fname = args.fname

    # create logger
    logs_home = os.path.join(str(pathlib.Path.home()), 'logs')

    # make sure logs directory exists
    if not os.path.exists(logs_home):
        os.makedirs(logs_home)

    lfname = os.path.join(logs_home, 'tomopy_' + datetime.strftime(datetime.now(), "%Y-%m-%d_%H_%M_%S") + '.log')
 
    log.setup_custom_logger(lfname)
    log.info("Saving log at %s" % lfname)

    if os.path.isfile(fname): 
        meta = dxreader.read_dx_meta(fname)  
        log.info(meta)
    else:
        log.info("File Name does not exist: ", fname)

if __name__ == "__main__":
    main(sys.argv[1:])
